/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "mastergui.h"

FD_mastergui *create_form_mastergui(void)
{
  FL_OBJECT *obj;
  FD_mastergui *fdui = (FD_mastergui *) fl_calloc(1, sizeof(*fdui));

  fdui->mastergui = fl_bgn_form(FL_NO_BOX, 810, 360);
  obj = fl_add_box(FL_UP_BOX,0,0,810,360,"");
    fl_set_object_lcolor(obj,FL_BLUE);
  fdui->exit = obj = fl_add_button(FL_NORMAL_BUTTON,740,10,50,20,"EXIT");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_INACTIVE,FL_COL1);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);

  fdui->schemas = fl_bgn_group();
  fdui->act0 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,90,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fps0 = obj = fl_add_text(FL_NORMAL_TEXT,220,90,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis0 = obj = fl_add_button(FL_PUSH_BUTTON,200,90,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->fps1 = obj = fl_add_text(FL_NORMAL_TEXT,220,110,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis1 = obj = fl_add_button(FL_PUSH_BUTTON,200,110,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->act1 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,110,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fps2 = obj = fl_add_text(FL_NORMAL_TEXT,220,130,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis2 = obj = fl_add_button(FL_PUSH_BUTTON,200,130,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->act3 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,150,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fps3 = obj = fl_add_text(FL_NORMAL_TEXT,220,150,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis3 = obj = fl_add_button(FL_PUSH_BUTTON,200,150,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->act4 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,170,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fps4 = obj = fl_add_text(FL_NORMAL_TEXT,220,170,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis4 = obj = fl_add_button(FL_PUSH_BUTTON,200,170,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vis5 = obj = fl_add_button(FL_PUSH_BUTTON,200,190,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vis6 = obj = fl_add_button(FL_PUSH_BUTTON,200,210,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vis7 = obj = fl_add_button(FL_PUSH_BUTTON,200,230,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vis8 = obj = fl_add_button(FL_PUSH_BUTTON,200,250,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vis9 = obj = fl_add_button(FL_PUSH_BUTTON,200,270,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->fps5 = obj = fl_add_text(FL_NORMAL_TEXT,220,190,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fps6 = obj = fl_add_text(FL_NORMAL_TEXT,220,210,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fps7 = obj = fl_add_text(FL_NORMAL_TEXT,220,230,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fps8 = obj = fl_add_text(FL_NORMAL_TEXT,220,250,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fps9 = obj = fl_add_text(FL_NORMAL_TEXT,220,270,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->act5 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,190,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->act6 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,210,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->act7 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,230,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->act8 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,250,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->act9 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,270,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fl_end_group();


  fdui->jdegui = fl_bgn_group();
  fdui->guifps = obj = fl_add_text(FL_NORMAL_TEXT,20,20,60,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,80,20,50,20,"jdegui");
    fl_set_object_color(obj,FL_COL1,FL_COL1);
    fl_set_object_lcolor(obj,FL_YELLOW);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fl_end_group();

  fdui->fps10 = obj = fl_add_text(FL_NORMAL_TEXT,220,290,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis10 = obj = fl_add_button(FL_PUSH_BUTTON,200,290,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->act10 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,290,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  obj = fl_add_text(FL_NORMAL_TEXT,200,60,90,30,"Schemas");
    fl_set_object_color(obj,FL_COL1,FL_LIGHTER_COL1);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);

  fdui->actuators = fl_bgn_group();
  fdui->motors = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,300,70,20,"motors");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->pantiltmotors = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,320,70,20,"ptmot");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fpsmotors = obj = fl_add_text(FL_NORMAL_TEXT,40,300,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fpspantiltmotors = obj = fl_add_text(FL_NORMAL_TEXT,40,320,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vismotors = obj = fl_add_button(FL_PUSH_BUTTON,20,300,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vispantiltmotors = obj = fl_add_button(FL_PUSH_BUTTON,20,320,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fl_end_group();


  fdui->sensors = fl_bgn_group();
  fdui->sonars = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,130,70,20,"sonars");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->robot = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,110,70,20,"encoders");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->frame_rateA = obj = fl_add_text(FL_NORMAL_TEXT,40,170,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->laser = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,90,70,20,"laser");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->colorimageA = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,170,70,20,"colorA");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->frame_rateB = obj = fl_add_text(FL_NORMAL_TEXT,40,190,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->colorimageB = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,190,70,20,"colorB");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->pantilt_encoders = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,150,70,20,"ptencod");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->fpslaser = obj = fl_add_text(FL_NORMAL_TEXT,40,90,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fpssonars = obj = fl_add_text(FL_NORMAL_TEXT,40,130,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fpsencoders = obj = fl_add_text(FL_NORMAL_TEXT,40,110,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fpspantiltencoders = obj = fl_add_text(FL_NORMAL_TEXT,40,150,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vislaser = obj = fl_add_button(FL_PUSH_BUTTON,20,90,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->visrobot = obj = fl_add_button(FL_PUSH_BUTTON,20,110,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vissonars = obj = fl_add_button(FL_PUSH_BUTTON,20,130,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->vispantiltencoders = obj = fl_add_button(FL_PUSH_BUTTON,20,150,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->viscolorimageA = obj = fl_add_button(FL_PUSH_BUTTON,20,170,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->viscolorimageB = obj = fl_add_button(FL_PUSH_BUTTON,20,190,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->frame_rateC = obj = fl_add_text(FL_NORMAL_TEXT,40,210,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->frame_rateD = obj = fl_add_text(FL_NORMAL_TEXT,40,230,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->colorimageC = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,210,70,20,"colorC");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->colorimageD = obj = fl_add_lightbutton(FL_PUSH_BUTTON,80,230,70,20,"colorD");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->viscolorimageC = obj = fl_add_button(FL_PUSH_BUTTON,20,210,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->viscolorimageD = obj = fl_add_button(FL_PUSH_BUTTON,20,230,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fl_end_group();

  obj = fl_add_text(FL_NORMAL_TEXT,20,60,90,30,"Sensors");
    fl_set_object_color(obj,FL_COL1,FL_LIGHTER_COL1);
    fl_set_object_lcolor(obj,FL_BLUE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  obj = fl_add_text(FL_NORMAL_TEXT,20,270,90,30,"Actuators");
    fl_set_object_color(obj,FL_COL1,FL_LIGHTER_COL1);
    fl_set_object_lcolor(obj,FL_RED);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->fps11 = obj = fl_add_text(FL_NORMAL_TEXT,220,310,40,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->vis11 = obj = fl_add_button(FL_PUSH_BUTTON,200,310,20,20,"");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_COL1,FL_YELLOW);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
  fdui->act11 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,310,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->act2 = obj = fl_add_lightbutton(FL_PUSH_BUTTON,260,130,120,20,"");
    fl_set_object_boxtype(obj,FL_NO_BOX);
    fl_set_object_color(obj,FL_COL1,FL_DARKTOMATO);
    fl_set_object_lcolor(obj,FL_DARKTOMATO);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
  fdui->hide = obj = fl_add_button(FL_NORMAL_BUTTON,680,10,50,20,"HIDE");
    fl_set_object_boxtype(obj,FL_FRAME_BOX);
    fl_set_object_color(obj,FL_DARKCYAN,FL_COL1);
    fl_set_object_lcolor(obj,FL_CYAN);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
  obj = fl_add_text(FL_NORMAL_TEXT,420,10,90,30,"Hierarchy");
    fl_set_object_color(obj,FL_COL1,FL_LIGHTER_COL1);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fdui->hierarchy = obj = fl_add_frame(FL_ENGRAVED_FRAME,430,40,360,300,"");
  fl_end_form();

  fdui->mastergui->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

